language: generic
sudo: required
dist: trusty
os:
- linux
- osx
cache:
- directories:
  - "$HOME/emacs"
matrix:
  fast_finish: true
  allow_failures:
  - env: EMACS_VERSION=snapshot
  - env: EMACS_VERSION=25.1
  - env: EMACS_VERSION=25.2
  - env: EMACS_VERSION=25.3
env:
  global:
  - EMAKE_SHA1=2dec3626e073c3b4aa88fbedd7ad5d27e530f470
  matrix:
  - EMACS_VERSION=25.1
  - EMACS_VERSION=25.2
  - EMACS_VERSION=25.3
  - EMACS_VERSION=26.1
  - EMACS_VERSION=snapshot
before_install:
- wget "https://raw.githubusercontent.com/vermiculus/emake.el/${EMAKE_SHA1}/emake.mk"
- make setup
install:
- make install
script:
# test uncompiled
# - make test-ert
# - make test-buttercup
# test compilation
- make compile
# test compiled
# - make test-ert
# - make test-buttercup
# linting
- make lint-package-lint
- make lint-checkdoc
