name: 'test'
on: { push: { paths: [ '**.el' ] } }
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version: ["26.1","26.2","26.3","27.1","27.2","snapshot"]
    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        cat <(jq -r '.nodes.root.inputs | map(.) | .[]' .nomake/flake.lock) \
            <(jq -r 'keys | .[]' .nomake/archive.lock) \
             \
            | xargs emacs -batch -l package --eval \
            "(progn
                (push '(\"melpa\" . \"https://melpa.org/packages/\")
                      package-archives)
                (package-initialize)
                (when command-line-args-left
                  (package-refresh-contents))
                (dolist (package-name command-line-args-left)
                  (let ((package (intern package-name)))
                     (when (and package
                                (not (memq package
                                           '(org-reverse-datetree))))
                       (package-install (cadr (assq package 
                                                    package-archive-contents)))))))"
    - name: Byte-compile
      if: ${{ true }}
      run: |
        emacs -batch -l bytecomp -l package --eval "(package-initialize)" -L . \
          --eval "(setq byte-compile-error-on-warn t)" \
          -f batch-byte-compile 'org-reverse-datetree.el'
    - run: |
        emacs -l package --eval "(package-initialize)" -L . -batch -l buttercup -f buttercup-run-discover "$PWD"
      name: Run buttercup tests
